### PR TITLE
Avoid failling collective operations in FastPM.py

### PR DESCRIPTION
**Pull request by rainwoodman**
Let's see if this works.

### CODE REVIEW

**Comment by nickhand** [comment]
This does not work....it seems like it could be a bug in bigfile? One rank always makes it through the try/except, but the others never do

**Comment by rainwoodman** [comment]
I thought I fixed a bug like this.. Let me take a look.

**Comment by rainwoodman** [comment]
I tagged a new bigfile that may help? 0.1.34.

**Comment by nickhand** [comment]
Yep that appears to fixed it. I think you need to push the tag to GitHub so it deploys to pypi. 

I'll merge this cleaner version into #349

**Comment by rainwoodman** [comment]
OK. Closing this one then.

**Pull request closed without merging**
