### PR TITLE
Add explicit optional argument, due to the change of default options in mcfit

### PR DESCRIPTION
**Pull request by eelregit**

### CODE REVIEW

**Comment by rainwoodman** [comment]
travis fails. Looks like you shall tag a version and make a release on pypi, or do something like that?

**Comment by eelregit** [comment]
... Why it didn't fail for python 3.5?

**Comment by rainwoodman** [comment]
Its probably failing due to another issue related to sympy which stucks at
an older veraipn on 3.5. So your PR is working.

I will merge both later today and make a release. Thanks!

**Comment by rainwoodman** [comment]
Green and merged. Thanks!

**Comment by eelregit** [comment]
Thanks a lot :)

**Pull request merged**
