### PR TITLE
Fix painting bug in CatalogMesh

### PR DESCRIPTION
**Pull request by sjforeman**
Fix bug from issue https://github.com/bccp/nbodykit/issues/575

### CODE REVIEW

**Comment by sjforeman** [comment]
Okay, so this build fails in Python 2.7 and 3.6, but passes in 3.5. Even if I reverse my changes (which are just moving one line of code around in source/mesh/catalog.py) and test in a new conda environment, e.g.
```
conda create -n nbodykit-dev python=2
source activate nbodykit-dev
conda install -c bccp --file requirements.txt --file requirements-extras.txt
pip install -e .
python run-tests.py --with-coverage --html-cov
```
I still get a failure in the same place (`test_cache.py`). This makes me wonder whether the failure isn't due to my change, but some other change that was made since the last build. Any thoughts?

**Comment by rainwoodman** [comment]
You are right it is irrelevant.

This seems to be a bug of cachey, but I am not sure why and how we are only triggering it now.

**Comment by rainwoodman** [comment]
This is reproducible on the nbodykit master branch.

Cachey issue filed at https://github.com/dask/cachey/issues/16

I will merge this PR as is. Thanks!

**Comment by sjforeman** [comment]
Great - thanks for looking into that!

**Pull request merged**
