### PR TITLE
Adding PeriodicPower with working YAML reader and cmd-line parser combo

### PR DESCRIPTION
**Pull request by nickhand**
This PR implements:

* `ReadConfigFile` action in `nbodykit.plugins` that reads a YAML file and checks various things using the underlying parser actions
* plugins.ArgumentParser returns namespace from YAML file when passed via `-c`, `--config`; the preparser also loads any plugins specified with `X` in YAML file
* PeriodicPower algorithm now working
* power examples updated to use nbkit.py PeriodicPower and the -c syntax (or @filename for one case) 
* no changes so far to power.py -- everything there should still work

### CODE REVIEW

**Comment by rainwoodman** [comment]
I did some refactoring work -- merging AlgorithmPluginMount with PluginMount. 

Would it be easier if you rebase this on #128, since that PR reduced the size of the code base?

**Comment by nickhand** [comment]
There are a couple of small fixes for this PR I was working on so let me pull your changes into my local branch and I'll put in a PR for everything

**Comment by rainwoodman** [comment]
A few more points. I realized argparse also describes the type of the kwarg
so it makes more sense to go from argparse to defaults of --init-- than
splitting them to two places.

Then plugins.argument parser really is "auto load argument parser".  It
shall only be used by nbkit.

Yu

**Comment by nickhand** [comment]
Okay, I think I see what you're trying to do. Let me rework the config parsing a bit to match this new API

**Pull request merged**
