### PR TITLE
adding in Grid datasource and GridPainter

### PR DESCRIPTION
**Pull request by nickhand**

### CODE REVIEW

**Comment by rainwoodman** [comment]
Hmm. How do I generate a grid file?

**Comment by nickhand** [comment]
Right now it's just the flattened Nmesh x Nmesh x Nmesh `real` array saved as a binary file, it would be easy to generate a density field with no correlations for testing purposes

**Comment by rainwoodman** [comment]
Yes. Alternatively, we can add a tool that produces a density grid from a data source and a painter argument?

**Comment by nickhand** [comment]
Yes, this would be useful I think. It's not exactly trivial to reconstruct
the full (Nmesh,)*Ndim array from the individual ranks (assuming we want to
save the full grid as one binary file)

**Pull request merged**
