### PR TITLE
updates to mockmaker in prep for Source objects 

### PR DESCRIPTION
**Pull request by nickhand**
these are updates towards #248 and #249 

we will incorporate into v2.0 of nbodykit, rather than master

### CODE REVIEW

**Comment by rainwoodman** [comment]
Be aware you are on a branch.

**Comment by nickhand** [comment]
yeah that was the original plan. I guess now that we made the stable 0.1.4 release, we could just merge this into master? 

I was just going to cherry-pick the things we wanted from this branch into the v2.0 branch

**Comment by rainwoodman** [comment]
It does sound a bit strange that 0.1.4 is not tagged off master.

**Comment by nickhand** [comment]
okay so, I'll merge this into master for v0.1.5.dev0

**Pull request merged**
