### PR TITLE
Add support to PCS resampling windows.

### PR DESCRIPTION
**Pull request by rainwoodman**
This requires version 0.1.37 of pmesh.

### CODE REVIEW

**Comment by rainwoodman** [comment]
What do you mean?

**Comment by nickhand** [comment]
Change the behavior so when you set ``compensated=True``, it uses CompensateCIC (TSC,PCS), etc
to do the window de-convolution (vs the current behavior which uses CompensateCICAliasing)

**Comment by nickhand** [comment]
I've pinned our conda build version to <3.1 so we can build the new pmesh and opened an issue about the error we are seeing

**Comment by rainwoodman** [comment]
Why do we want to change the behavior? The current compensation makes sure that the shotnoise spectrum is flat. If you change it it's no longer flat I suppose.

**Pull request merged**
